services:
  - type: web
    name: scrambleclip2
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      python -m streamlit run app.py --server.port $PORT --server.enableCORS false --server.enableXsrfProtection false
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONPATH
        value: /app
      - key: IMAGEMAGICK_BINARY
        value: /usr/bin/convert
      - key: FFMPEG_BINARY
        value: /usr/bin/ffmpeg
    healthCheckPath: /
    # Use Render's native apt packages support
    apt:
      packages:
        - ffmpeg
        - libsm6
        - libxext6
        - libgl1-mesa-glx
        - python3-dev
        - imagemagick
        - libmagickwand-dev
        - ghostscript
        - poppler-utils 